
language: python
sudo: true
python: 2.7

dist: precise

branches:
    only:
        - master1

os:
  - linux

compiler:
  - gcc


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install libboost1.55-dev
  - sudo apt-get update -qq
  - sudo apt-get -qq install gcc-4.9
  - sudo apt-get -qq install g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - sudo apt-get install libopenblas-dev libblas-dev libarpack++2-dev liblapack-dev
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - sudo apt-get update


# the 'install' is a modification of https://github.com/johnlees/seer/blob/master/.travis.yml  AND
#                                    https://github.com/dme65/SOT/blob/master/.travis.yml

install:
 - sudo apt-get install -qq cmake
 - wget http://sourceforge.net/projects/arma/files/armadillo-7.600.2.tar.xz     
 - tar xf armadillo-7.600.2.tar.xz
 - cd armadillo-7.600.2/
 - cmake .
 - make
 - sudo make install
 - cd ..
 - pip --version
 - cython --version
# - python setup.py install

script:
  - python setup.py install && py.test

#script:
 # - py.test test --cov=codecov

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change



