
language: python
sudo: true
python: 2.7

dist: precise

branches:
    only:
        - master1

os:
  - linux

compiler:
  - gcc

#env:
#  global:
#    - CMAKE_BUILD_TYPE=RELEASE


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.9 liblapack-dev libboost-program-options-dev -y
  - pip install -r requirements.txt
  - sudo apt-get update

install:
 - wget http://sourceforge.net/projects/arma/files/armadillo-7.600.2.tar.gz     
 - tar xzf armadillo-7.600.2.tar.gz
 - pushd armadillo-7.600.2 && CXX=/usr/bin/g++-4.9 cmake . && make && sudo make install && popd
 - pip --version
 - cython --version

script:
  - python setup.py build
  - python setup.py sdist
  #- py.test
  - python setup.py install && py.test

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change



