
language: python
sudo: true
python: 2.7

dist: precise


branches:
    only:
        - master1

os:
  - linux

compiler:
  - gcc

#env:
#  global:
#    - CMAKE_BUILD_TYPE=RELEASE


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:comp-phys/stable
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 libarmadillo-dev libarmadillo4 libboost1.54-all-dev
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - sudo cp /home/travis/config.hpp /usr/include/armadillo_bits/config.hpp
  - pip install -r requirements.txt
  - sudo apt-get update
  
install:
  - mkdir build && cd build && cmake -DDEBUG=OFF -DPROFILE=OFF .. && make -j4
  - pip --version
  - cython --version

script:
  - python setup.py build
  - python setup.py sdist
  #- py.test
  - python setup.py install && py.test

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change



