
language: python
sudo: true
python: 2.7

dist: precise

branches:
    only:
        - master1
os:
  - linux

compiler:
  - gcc


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y          # ppa to install both g++-4.9, gcc-4.9
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:boost-latest/ppa -y                 # ppa to install the boost version 1.55 
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.55-dev libboost-filesystem1.55-dev libboost-locale1.55-dev       # install boost (including locale and boost-system)
  - sudo apt-get -qq install gcc-4.9
  - sudo apt-get -qq install g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - sudo apt-get install libopenblas-dev libblas-dev libarpack++2-dev liblapack-dev       # armadillo requirements
  - pip install -r requirements.txt
  - pip install pytest codecov pytest-cov
  - sudo apt-get update



install:
 - sudo apt-get install -qq cmake                                                # install cmake
 - wget http://sourceforge.net/projects/arma/files/armadillo-7.600.2.tar.xz      # download, build, install the latest armadillo version
 - tar xf armadillo-7.600.2.tar.xz
 - cd armadillo-7.600.2/
 - cmake .
 - make
 - sudo make install
 - cd ..
 - pip --version
 - cython --version
 #- python setup.py install

#script:
#  - python setup.py install && py.test

script:
  - python setup.py develop && py.test --cov=textTinyPy
  #- py.test --cov=textTinyPy
  #- py.test -v --cov-config .coveragerc --cov textTinyPy test/

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change



