
language: python
sudo: true
python: 2.7

dist: precise


branches:
    only:
        - master1

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
            #- llvm-toolchain-precise-3.7
            - boost-latest
        packages:
            - cmake
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-locale1.55-dev
            #- clang-3.7
            #- g++-5
            #- gcc-5

os:
  - linux

compiler:
  - gcc

env:
  global:
    - CMAKE_BUILD_TYPE=RELEASE


before_install:
  - python --version
  - pip install pytest pytest-cov
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get -qq update; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get -qq install gcc-4.8; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get -qq install g++-4.8; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libgfortran3; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libarmadillo-dev; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libarmadillo2; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get update; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libopenblas-dev; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libblas-dev liblapack-dev; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get update; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install libarpack++2-dev; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get install gfortran; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so; fi
  - if [[ \"$TRAVIS_OS_NAME\" == \"linux\" ]]; then sudo apt-get update; fi

install:
  - pip --version
  - pip install -r requirements.txt

script:
  - python setup.py install && py.test

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change



